blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://discord.gg/tSqtvHUJzE
    about: You can join the discussions on Discord.
  - name: Chat
    url: https://github.com/Avdhesh-Varshney/WebMasterLog/discussions
    about: You can chat with the community on GitHub Discussions.
  - name: Login does not work
    url: https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md
    about: Before opening a new issue, please make sure to read CONTRIBUTING.md
